function Inversiones() {
    return (
        <section className="padded">
            <div className="container">
                <h2>Inversiones</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias nihil nam error quibusdam. Repellat eveniet quibusdam, soluta doloremque quae rerum tempora ea consequatur fugit ipsa libero iusto nam consequuntur earum explicabo, aut animi in ipsum porro numquam sapiente. Vitae nostrum, fugit soluta voluptas aut mollitia facere eveniet quibusdam minima ipsa optio impedit, obcaecati velit iusto earum perspiciatis ipsum ullam recusandae corporis odit. Quaerat assumenda ut earum ea nesciunt est nulla perferendis, necessitatibus error ducimus totam, quis esse! Itaque, maxime illo!</p>
                <p>Inventore facere mollitia sunt aspernatur enim corporis officiis, unde magni saepe nobis culpa animi sapiente deleniti ducimus vitae vel nihil assumenda fuga praesentium hic fugit illum molestias incidunt? Suscipit libero dicta excepturi quos asperiores voluptas amet quas eaque culpa soluta aperiam inventore enim natus praesentium aliquid cumque vitae labore perspiciatis, nostrum ullam magnam quia consequatur rem. Sunt neque ipsum omnis ad obcaecati hic quisquam vel doloremque nostrum, vero sit, suscipit in quia eos architecto soluta odio. Dolores, cum obcaecati. Perspiciatis.</p>
                <p>Quam numquam nulla impedit, ipsa minima molestiae eum eos optio distinctio inventore temporibus, praesentium vitae ullam obcaecati enim. Animi quod numquam tempore culpa ex omnis mollitia sapiente magnam sunt cumque quaerat, ad quae quidem esse neque recusandae, ducimus natus a aut qui itaque? Nemo expedita eligendi modi magni officia aliquam illum velit tenetur unde, cumque esse facere veniam rem amet? Perspiciatis, est impedit illo minima voluptates vero. Nam at beatae architecto dolorum fugit. Cumque fugiat, sed laborum quam ut facilis.</p>
                <p>Eos aliquam consequatur expedita iure, sequi est repudiandae libero dolore illo dolorem saepe porro earum rerum numquam totam reiciendis aut! Atque ab eligendi, nisi necessitatibus odit, cumque laudantium obcaecati asperiores odio perspiciatis aliquam ipsum! Rem porro voluptatibus velit. Praesentium, dolores dolore. Libero explicabo quis tempora porro, placeat impedit est molestiae debitis corrupti ab, molestias modi nisi quia! Porro adipisci consequuntur, esse inventore nesciunt id et fugiat hic rerum sequi ut earum sapiente ea voluptate quia dolores officia doloremque doloribus vitae.</p>
                <p>Quisquam, esse saepe hic voluptatibus fuga facere voluptas ad sed dolore delectus voluptates sint veritatis vel ratione ducimus consectetur? Quod porro voluptate sint, nesciunt eaque eveniet molestiae inventore odit rerum libero saepe, dicta veniam alias minima nobis consequatur ut esse officiis. Maiores earum hic perspiciatis commodi in dolor veritatis necessitatibus suscipit aliquid doloremque voluptate atque enim exercitationem ullam laborum, inventore fugiat, magnam placeat, sunt totam animi. Debitis, corrupti quidem! Recusandae ea omnis ullam porro magni quisquam id libero quidem architecto?</p>
                <p>In alias ea debitis inventore maiores aperiam, amet vitae labore temporibus obcaecati aliquid laudantium, harum sapiente nisi cumque fugiat quae dolores ipsum quas sequi nostrum. Suscipit similique vitae accusantium amet distinctio. Ipsa quod mollitia, deserunt ea ducimus qui eligendi neque quas tenetur unde consectetur consequuntur natus dolore reprehenderit? Libero culpa maxime facere, dicta sit nihil, omnis incidunt, ex dignissimos sed cupiditate minus magnam? Quod officia porro cumque voluptate, eius sed sint eligendi ipsum qui dolorum architecto earum, totam deleniti quasi?</p>
            </div>
        </section>
    )
}

export default Inversiones